<?php

return [
    'afwezigheid' => [
        'name' => 'Ketidakhadiran (Afwezigheid)',
        'description' => 'Pengurusan harta kekayaan orang yang berdasarkan penetapan pengadilan dinyatakan tidak hadir.',
        'requirements' => ['Penetapan Pengadilan Negeri', 'Surat permohonan', 'Identitas pemohon', 'Bukti-bukti kepemilikan harta', 'Dokumen lain yang dianggap penting'],
        'duration' => '6 hingga 12 bulan.',
        'tariffs' => ['Penjualan harta kekayaan barang tetap dan/atau barang bergerak: 2,5% dari hasil penjualan per budel.', 'BHP selaku pelaksana ketidakhadiran: 7% dari jumlah harta peninggalan.', 'Pengurusan berakhir sebelum batas waktu penyelesaian: 3,5% dari jumlah seluruh kekayaan/harta peninggalan.'],
        'procedure' => ['Pemohon mengajukan permohonan beserta dokumen persyaratan kepada Kepala BHP Medan.', 'Permohonan dicatat, didisposisikan, dan diproses oleh Kurator Keperdataan.', 'BHP mengumumkan ketidakhadiran pada koran nasional, koran lokal, dan Berita Negara serta memberitahukan instansi terkait.', 'Kurator memanggil pemohon dan membuat Berita Acara Pencatatan Harta.', 'BHP memproses sewa, permohonan pembelian, izin jual, penetapan pengadilan, dan penilaian appraisal sesuai kebutuhan.', 'Petugas memeriksa dan memungut PNBP.', 'Akta jual beli ditandatangani di hadapan notaris dan diserahkan kepada pemohon.'],
        'product' => 'Akta Jual Beli Harta Kekayaan Orang yang Dinyatakan Tidak Hadir.',
        'source_pages' => '5–6',
    ],
    'wasiat' => [
        'name' => 'Pendaftaran dan Pembukaan Wasiat',
        'description' => 'Pendaftaran wasiat terbuka atau pembukaan dan pembacaan wasiat tertutup atau rahasia.',
        'requirements' => ['Surat permohonan asli bermeterai Rp10.000', 'Akta kematian', 'Surat wasiat asli', 'Identitas ahli waris', 'Surat Keterangan Wasiat asli dari Pusat Daftar Wasiat Ditjen AHU'],
        'duration' => 'Paling lambat 3 hari kerja, disesuaikan dengan alur proses.',
        'tariffs' => ['Pendaftaran wasiat terbuka/umum: Rp200.000 per akta.', 'Pendaftaran wasiat tertutup/rahasia: Rp500.000 per wasiat.'],
        'procedure' => ['Pemohon mengajukan permohonan beserta persyaratan kepada Kepala BHP.', 'Permohonan didisposisikan kepada Seksi Harta Peninggalan untuk diproses Kurator Keperdataan.', 'Petugas mencatat, menyiapkan bahan, dan meneruskan berkas.', 'Kurator menelaah dan memverifikasi berkas serta menyiapkan hasil rapat.', 'Kepala menetapkan permohonan untuk ditolak atau diproses.', 'Jika diterima, pemohon dipanggil untuk pembuatan akta atau pembukaan dan pembacaan wasiat.', 'Kepala BHP menandatangani akta atau berita acara.'],
        'product' => 'Akta Wasiat Terbuka atau Berita Acara Pembukaan dan Pembacaan Wasiat Tertutup/Rahasia.',
        'source_pages' => '9',
    ],
    'kepailitan' => [
        'name' => 'Kepailitan',
        'description' => 'Pengurusan dan pemberesan harta pailit ketika BHP ditunjuk sebagai Kurator Negara.',
        'requirements' => ['Penetapan atau putusan pailit dari Pengadilan Niaga'],
        'duration' => '6 hingga 12 bulan, disesuaikan dengan alur proses yang terjadi.',
        'tariffs' => ['Penjualan barang tetap dan/atau bergerak melalui lelang atau di bawah tangan: 2,5% dari hasil penjualan per budel.', 'Pelaksanaan likuidasi perseroan persekutuan modal: 2,5% dari nilai harta likuidasi per budel.'],
        'procedure' => ['Pengadilan Niaga menyampaikan putusan pailit kepada Kepala BHP.', 'BHP menyiapkan rencana kerja, penunjukan, pengumuman, dan data pendukung.', 'Kurator mengadakan rapat kreditor dan melakukan verifikasi tagihan.', 'Kurator menginventarisasi, memverifikasi, dan melakukan sita umum atas aset.', 'Penilai publik menilai aset sebagai dasar penjualan melalui KPKNL atau mekanisme yang ditetapkan.', 'Hasil penjualan dibagi berdasarkan penetapan Hakim Pengawas dan PNBP disetorkan.', 'Kurator mengajukan pengakhiran kepailitan serta melaporkan pelaksanaannya kepada Ditjen AHU.'],
        'product' => 'Penetapan Likuidasi, Penetapan Pengakhiran Kepailitan, dan Dokumen Laporan Pengakhiran.',
        'source_pages' => '12–13',
    ],
    'uang-pihak-ketiga' => [
        'name' => 'Penatausahaan Uang Pihak Ketiga',
        'description' => 'Penerimaan dan penatausahaan uang pihak ketiga yang diserahkan oleh instansi atau lembaga.',
        'requirements' => ['Surat permohonan Uang Pihak Ketiga dari instansi atau lembaga', 'Data dukung lain yang diperlukan'],
        'duration' => '3 hari.',
        'tariffs' => ['Penyerahan Uang Pihak Ketiga setelah 30 tahun: 100% dari uang yang ditetapkan Pengadilan Negeri untuk diserahkan ke Kas Negara per budel.'],
        'procedure' => ['Pengguna layanan mengirimkan surat permohonan beserta data dukung kepada Kepala BHP Medan.', 'Permohonan didisposisikan kepada Seksi Harta Peninggalan.', 'Kurator menelaah permohonan dan menyusun Berita Acara Serah Terima.', 'Kepala BHP menyetujui dan menandatangani Berita Acara Serah Terima.'],
        'product' => 'Berita Acara Serah Terima Uang Pihak Ketiga.',
        'source_pages' => '16',
    ],
    'perwalian' => [
        'name' => 'Perwalian',
        'description' => 'Pengawasan wali serta perlindungan hak dan harta anak yang berada di bawah perwalian.',
        'requirements' => ['Surat permohonan asli bermeterai Rp10.000', 'Penetapan perwalian', 'Akta kematian', 'Surat ganti nama jika ada', 'Fotokopi akta kelahiran anak', 'Surat kawin', 'Surat cerai', 'Identitas wali anak', 'Surat Keterangan Wasiat jika ada', 'Dokumen pendukung lainnya'],
        'duration' => 'Permohonan diproses 5 hingga 8 jam kerja; proses lanjutan bersifat tentatif.',
        'tariffs' => ['Sumpah perwalian tanpa harta: Rp0 per permohonan.', 'Sumpah perwalian dengan harta: Rp200.000 per permohonan.', 'Persetujuan wali untuk menjual harta: Rp200.000 per surat.', 'Pengakhiran perwalian tanpa harta: Rp0.', 'Pengakhiran perwalian dengan harta: Rp50.000.', 'Salinan dokumen tanpa harta yang hilang/rusak: Rp0.', 'Salinan dokumen dengan harta yang hilang/rusak: Rp50.000.'],
        'procedure' => ['Pemohon mengirimkan permohonan dan dokumen pendukung kepada Kepala BHP.', 'Permohonan didisposisikan dan ditelaah oleh Kurator Keperdataan.', 'BHP memverifikasi berkas dan menetapkan permohonan diterima atau ditolak.', 'Jika diterima, dilakukan penghadapan dan pencatatan harta.', 'Kurator mengambil sumpah wali dan melaksanakan pengawasan.', 'Jika diperlukan, dilakukan pengakhiran atau penggantian wali dan pembayaran PNBP.'],
        'product' => 'Berita Acara Penyumpahan, Berita Acara Penghadapan, dan Surat Keterangan Persetujuan Penjualan Harta/Kekayaan.',
        'source_pages' => '19–20',
    ],
    'pengampuan' => [
        'name' => 'Pengampuan',
        'description' => 'Pengawasan pengampu dan perlindungan orang serta harta yang berada di bawah pengampuan.',
        'requirements' => ['Surat permohonan asli bermeterai Rp10.000', 'Penetapan pengampuan', 'Identitas pengampu', 'Identitas orang yang berada di bawah pengampuan', 'Bukti kekayaan orang yang berada di bawah pengampuan', 'Dokumen pendukung lainnya'],
        'duration' => 'Permohonan diproses 5 hingga 8 jam kerja; proses lanjutan bersifat tentatif.',
        'tariffs' => ['Sumpah pengampuan tanpa harta: Rp0 per permohonan.', 'Sumpah pengampuan dengan harta: Rp200.000 per permohonan.', 'Persetujuan pengampu untuk menjual harta: Rp200.000 per surat.', 'Pengakhiran pengampuan tanpa harta: Rp0.', 'Pengakhiran pengampuan dengan harta: Rp50.000.', 'Salinan dokumen tanpa harta yang hilang/rusak: Rp0.', 'Salinan dokumen dengan harta yang hilang/rusak: Rp50.000.'],
        'procedure' => ['Pemohon mengirimkan permohonan beserta dokumen pendukung kepada Kepala BHP.', 'Berkas didisposisikan kepada Seksi Wilayah dan ditelaah Kurator Keperdataan.', 'BHP memverifikasi berkas dan menetapkan permohonan diterima atau ditolak.', 'Jika diterima, dilakukan penghadapan dan pencatatan harta.', 'Kurator mengambil sumpah pengampu dan melaksanakan pengawasan.', 'Jika diperlukan, dilakukan pengakhiran atau penggantian pengampu dan pembayaran PNBP.'],
        'product' => 'Berita Acara Penyumpahan, Berita Acara Penghadapan, dan Surat Keterangan Persetujuan Penjualan Harta/Kekayaan.',
        'source_pages' => '23–24',
    ],
    'hak-waris' => [
        'name' => 'Surat Keterangan Hak Waris',
        'description' => 'Pembuatan Surat Keterangan Hak Waris dan Berita Acara Penghadapan oleh BHP Medan.',
        'requirements' => ['Surat permohonan asli bermeterai Rp10.000', 'Akta kematian', 'Akta perkawinan', 'Identitas ahli waris berupa KTP, KK, dan akta kelahiran', 'Surat Keterangan Wasiat asli dari Pusat Daftar Wasiat Ditjen AHU', 'Dokumen pendukung lainnya jika diperlukan'],
        'duration' => '1 hingga 3 hari kerja, disesuaikan dengan proses pembuatan.',
        'tariffs' => ['Pembuatan Surat Keterangan atau salinan Surat Keterangan Hak Waris: Rp200.000 per surat.'],
        'procedure' => ['Pemohon mengirimkan permohonan beserta dokumen pendukung kepada Kepala BHP.', 'Permohonan didisposisikan kepada Seksi Harta Peninggalan.', 'Kurator memverifikasi dan menelaah berkas.', 'BHP membuat konsep Surat Keterangan Hak Waris dan Berita Acara Penghadapan.', 'Dilakukan penghadapan dan verbal komparisi di hadapan pemohon, seluruh ahli waris, dan saksi.', 'Kepala BHP menyetujui dan menandatangani Surat Keterangan Hak Waris.'],
        'product' => 'Surat Keterangan Hak Waris dan Berita Acara Penghadapan.',
        'source_pages' => '27',
    ],
    'harta-tak-terurus' => [
        'name' => 'Harta Peninggalan Tidak Terurus',
        'description' => 'Pengurusan harta peninggalan yang tidak memiliki ahli waris atau pengurus yang diketahui.',
        'requirements' => ['Penetapan Pengadilan Negeri', 'Surat permohonan', 'Identitas pemohon', 'Bukti-bukti kepemilikan harta', 'Dokumen lain yang dianggap penting'],
        'duration' => '6 hingga 12 bulan.',
        'tariffs' => ['Penjualan harta kekayaan barang tetap dan/atau barang bergerak: 2,5% dari hasil penjualan per budel.', 'BHP selaku pelaksana harta tak terurus: 7% dari jumlah harta peninggalan.', 'Pengurusan berakhir sebelum batas waktu penyelesaian: 3,5% dari jumlah seluruh kekayaan/harta peninggalan.'],
        'procedure' => ['Pemohon mengajukan permohonan beserta dokumen persyaratan kepada Kepala BHP Medan.', 'Permohonan diperiksa, aset dicatat, dan dibuatkan berita acara.', 'BHP mengumumkan harta tak terurus pada koran nasional, koran lokal, dan Berita Negara serta memberitahukan instansi terkait.', 'Kurator memanggil pemohon dan membuat Berita Acara Pencatatan Harta.', 'BHP memproses sewa, permohonan pembelian, izin jual, penetapan pengadilan, dan penilaian appraisal sesuai kebutuhan.', 'Petugas memeriksa dan memungut PNBP.', 'Akta jual beli ditandatangani di hadapan notaris dan diserahkan kepada pemohon.'],
        'product' => 'Akta Jual Beli Harta yang Tidak Terurus.',
        'source_pages' => '30–31',
    ],
];
